@startuml

start

:Загрузить JSON-конфигурацию;
:Проверить обязательные поля;

if (Команда?) then (configure)
  :Создать резервную копию .config;
  :Запустить make nconfig (интерактивно);
  :Сохранить .config как .config.latest;
  stop
elseif (build) then
  :Выполнить make bzImage modules -jN;
  :Установить флаг "ядро собрано";
  stop
elseif (install) then
  :Проверить флаг сборки;
  :Прочитать параметры единственного устройства;
  :Отмонтировать;
  :Смонтировать устройство;
  :Вывести содержимое до установки;
  if (Временная директория создана?) then (нет)
    :Создать временную директорию;
    :Выполнить make install INSTALL_PATH=temp_boot;
    :Выполнить genkernel --bootdir=temp_boot;
  endif 
  :Выполнить make modules_install;
  :Скопировать файлы с переименованием;
  :Найти путь к grub.cfg;
  :Обновить grub.cfg;
  :Установить GRUB (BIOS и UEFI);
  :Вывести содержимое после установки;
  :Отмонтировать устройство;
  stop
else
  :Ошибка: неизвестная команда;
  stop
endif

@enduml
